{% set name = "overviewpy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/overviewpy-{{ version }}.tar.gz
  sha256: 2b408440d272162d3ce9d2d82bae2005f6370dcfed3d0b24a4a047079a935d10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - matplotlib-base >=3.7.2
    - pandas >=2.0.3
    - jinja2 >=3.1.2

test:
  imports:
    - overviewpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cosimameyer/overviewpy
  doc_url: https://cosimameyer.github.io/overviewpy/
  summary: Easily Extracting Information About Your Data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
